### ISSUE TITLE
game crashes if nodebox is nil

### ISSUE THREAD

**Issue by berengma** [TheTermos/mobkit#3]
makes a server unplayable because game crashes repeatedly when a mob meets a node with nodebox = nil.

easy solution line 180:
if node.drawtype == 'nodebox' then
if node.node_box == nil then return nil end        -- <- This is new and to be added
if node.node_box.type == 'fixed' then

**Comment by TheTermos** [comment]
First I need to investigate why such a node exists, then maybe I'll be able to determine the height instead of making it impassable by returning nil. 

Would be grateful if you'd be kind to temporarily add this to your local fix and report the result:

if node.node_box == nil then
minetest.chat_send_all('nodeboxless: '.. node.name)
return nil
end

**Comment by berengma** [comment]
good idea.

i tried to find it with grep yesterday, but failed in using the right parameters and sorting output

**Comment by berengma** [comment]
it is farming_redo on Lilly:

2019-10-07 22:39:00: ACTION[Server]: [mobkit] farming:melon_8 uses nodebox without node_box defined

**Comment by berengma** [comment]
mobkit updated on server, until now it is save, even with players and mobs near melons
